### ISSUE TITLE
Improve deck collection

### ISSUE THREAD

**Issue by fspoettel** [fspoettel/arkham.build#10]
- [x] ~Decks should have a quick action menu. There should, for now, be actions for "Duplicate", "Edit", "Delete".~
- [x] Decks should be searchable. The search can for now only consider the _deck name_.
- [x] Decks should be filterable by:
    - [x] Tags
    - [x] Investigator
    - [x] Class
- [ ] Decks should be sortable by:
  - [ ] Name
  - [ ] Date updated (current default)
  - [ ] Date created
  - [ ] XP required

**Out of scope**

- [_My decks_ page](https://github.com/users/fspoettel/projects/5/views/1?pane=issue&itemId=67570796)
- [Deck archive](https://github.com/users/fspoettel/projects/5/views/1?pane=issue&itemId=67570798)

---

Even though the decks page is out of scope, we can already start thinking about it and can probably re-use a large chunk of stuff there if we keep it in mind.

One other consideration is to use the virtualized scroller for the deck collection, it would help with some of the very large collections I know people on arkhamdb have. I don't think we want pagination here?

**Comment by kidManuel** [comment]
I think this item can be moved to In Progress? 
I'm currently fleshing out the deck sorting!
