### ISSUE TITLE
Add a `LICENSE` for arkham.build

### ISSUE THREAD

**Issue by LastTalon** [fspoettel/arkham.build#107]
I’m interested in contributing to arkham.build and getting involved in the project’s development. However, I noticed that the repository does not currently include a `LICENSE` file, which can make it unclear for potential contributors about the terms of contribution and use. Without a clear license, there may be ambiguity around the ownership and permissions of contributed code.

It would be helpful to include a permissive license (such as MIT or CC0) in the repository to clarify that all contributions are made under the same terms and to ensure that arkham.build remains accessible for everyone who uses it. This would make it easier for contributors to understand how their work will be used and help prevent any potential future issues around code ownership or take-down requests.

I’ve enjoyed exploring arkham.build and believe adding a license could strengthen the project’s foundation and make contributions simpler and more secure. If you’d like any assistance with setting up a license file, I’d be happy to help! I’m also open to further discussing this issue or even making a PR to add the license if that’s easier.

**Comment by fspoettel** [comment]
Thanks for the nudge!
