### ISSUE TITLE
Add Arkhamdb sync

### ISSUE THREAD

**Issue by fspoettel** [fspoettel/arkham.build#12]
Ideally, we can support logging into the app via arkhamdb, which then should sync a user's decks and collection state to the local database, and vice versa.

**Comment by eike** [comment]
Maybe, as an intermediate solution, a deck export format could be added that is compatible with ArkhamDB's deck import parser. I think this would be very similar to the Markdown export, except that there cannot be dashes at the beginning of lines, and instead of "x2" after the card it needs to say "2x" in front of it. (So
```
2x Flashlight
```
instead of
```
- Flashlight x2
```
I'm not quite sure if the checked boxes for Customizable cards can be imported as well.)

**Comment by fspoettel** [comment]
@eike Thank you for the suggestion. I agree that would be nice, but the ArkhamDB import is unfortunately completely broken and does not work with a lot of newer content such as customizable, but also some other things such as parallel investigators, taboo, the list goes on.

Given that we are using the exact same format as the ArkhamDB JSON API, it's a bit of a shame that ArkhamDB does not have the option to import decks from JSON files.

**Comment by eike** [comment]
I see. The current state is a bit painful, though. I *love* building a deck on arkham.build. (Really, it's *so* nice, thank you!) But then, I want to use it in a campaign with ArkhamCards, and the only way I have found so far is to rebuild the deck using the ArkhamDB or ArkhamCards deckbuilder, or to copy the Markdown and to manually perform the changes mentioned above. Even if the import was not perfect, just getting to a state where I only have to select the customizations again (plus Parallel sides, etc.) would go a long way.

(If you are open to pull requests, I could also look into it on the weekend, maybe.)

**Comment by fspoettel** [comment]
I understand. The ArkhamDB sync is on the top of my list, kamalisk was nice enough to provide an API key already. Maybe we can do a very simple "export to arkhamdb" first and then add the bi-directional sync on top of it in a next step?

**Comment by fspoettel** [comment]
Update: I'm making some good progress here, almost at the point where this works with the initial API implementation I made a while back. Hope to get it deployed next week.

**Comment by fspoettel** [comment]
Until this is ready, [this user script](https://discord.com/channels/225349059689447425/1264242716179431670/1301639521095385168) can be used as a quick solution to import a deck.

**Comment by fspoettel** [comment]
Hey @eike, a first version of the arkhamdb sync is live. You can enable it in the settings. Let me know if you find any issues.

**Comment by eike** [comment]
I only had time for a very cursory look, but I liked what I saw very much. Thank you so much for this site! (If I find issues later, I will report.)
