### ISSUE TITLE
Some rendering issues around forbidden cards

### ISSUE THREAD

**Issue by 5argon** [fspoettel/arkham.build#130]
1. If deck was saved with a forbidden card before the edit, the card is no longer crossed out when quantity drops to 0 and the list still retain the card until you save, because validation error that was used to determine the card's forbidden status is gone.

<img width="409" alt="image" src="https://github.com/user-attachments/assets/a249024d-f4fe-4a14-baa2-a82fa724a7f7" />

<img width="397" alt="image" src="https://github.com/user-attachments/assets/35725ed3-934b-40d5-a29c-14401a7c4f72" />

2. When "Show unusable cards" is on, the card list now show all duplicates, and also the forbidden check is not performed on them so they always rendered in color instead of greyed out.

<img width="1493" alt="image" src="https://github.com/user-attachments/assets/8eca871e-7f40-4825-8c10-3b87a2baedb1" />

3. Validation error stuck with old values reproduced by this sequence (an extra Arcane Initiate error is added along the way) : 

https://github.com/user-attachments/assets/ddc573ba-643c-4a31-a12d-dc4d6d22e9ec

**Comment by fspoettel** [comment]
thanks for the report! I fixed the issues, albeit a bit differently in some cases:
For #1, I introduced a faded state for removed cards.
For #2, I fixed the bug with the crossinfg out, but left the behavior untouched thats shows all versions of a card. Until we have a proper version selector, this is the only way to change the exact version of a card.
