### ISSUE TITLE
Markdown links inside HTML tag not evaluated

### ISSUE THREAD

**Issue by 5argon** [fspoettel/arkham.build#48]
Markdown link in an HTML tag (`div`, `span`) like the following first 2 example worked on arkhamdb but not in arkham.build

```markdown
<div>
[**Tag, link, bold**](https://www.fantasyflightgames.com/en/products/arkham-horror-the-card-game/products/scarlet-keys-investigator-expansion/).
</div>

<div>
[Tag, link](https://www.fantasyflightgames.com/en/products/arkham-horror-the-card-game/products/scarlet-keys-investigator-expansion/).
</div>

[**Link, bold**](https://www.fantasyflightgames.com/en/products/arkham-horror-the-card-game/products/scarlet-keys-investigator-expansion/).

[Link](https://www.fantasyflightgames.com/en/products/arkham-horror-the-card-game/products/scarlet-keys-investigator-expansion/).
```

<img width="619" alt="image" src="https://github.com/user-attachments/assets/96f6f213-bb56-4219-8e06-8e7c4cd1c2f0">

<img width="170" alt="image" src="https://github.com/user-attachments/assets/a030b3e0-00d4-460d-b78c-922f7620f5ae">

**Comment by fspoettel** [comment]
We use a markdown parser that is compliant with the Markdown specs while ArkhamDB does not. There is a [spec-compliant](https://spec.commonmark.org/0.28/#html-blocks) way to make it work though, adding new lines around the markdown in html:

```
<div>

[**Tag, link, bold**](https://www.fantasyflightgames.com/en/products/arkham-horror-the-card-game/products/scarlet-keys-investigator-expansion/).

</div>
```

Does this work for you?

**Comment by 5argon** [comment]
That works, thanks!
