### ISSUE TITLE
On iOS, Edge Browser : 'Object.entries(t.asset).toSorted' is undefined 

### ISSUE THREAD

**Issue by 5argon** [fspoettel/arkham.build#51]
After loading the card database, received error code 500 :

```
 'Object.entries(t.asset).toSorted(([r],[o])=>O(r,o))', 'Object.entries(t.asset).toSorted' is undefined)
```

![image](https://github.com/user-attachments/assets/c70cc741-30ae-4859-bf92-6033f8010ccf)

**Comment by fspoettel** [comment]
Thanks for the report, looks like the inclusion of the very recent browser API without polyfill was a bit premature. I'll get this fixed for next release.
