### ISSUE TITLE
Add deck composition charts

### ISSUE THREAD

**Issue by fspoettel** [fspoettel/arkham.build#67]
**Describe the solution you'd like**

- [x] Add resource chart
- [x] Add icon chart
  - How to handle cards with multiple icons?
  - How to handle icons on important allies?
- [x] Add faction chart
- [ ] Stretch Goal: Add deck role charts (see screenshot)

![Image](https://github.com/user-attachments/assets/200e27a9-3ad8-43f8-a4bb-3adcc3c27464)

**Additional context**
From Discord, discussion starts [here](https://discord.com/channels/225349059689447425/1264242716179431670/1281098052966547486).

**Comment by kidManuel** [comment]
I've been thinking about this one as well, I really do use the resource cost curve chart in arkhamdb.
Problem is that the package size cost of the most popular charting libraries (D3, Highchart) is QUITE large.
Maybe we could cook a simple ad-hoc chart component and just write the logic ourselves? How hard could it be?

**Comment by fspoettel** [comment]
I think we can lazy load the chunk containing the charts library with a dynamic import, then it does not add to any initial chunk.

Library-wise, I'm quite fond of Victory.
